version: "3.7"

services:
  app:
    image: machineplay/gcc10-standard-env
    command: sh -c "/bin/bash"
    container_name: double-buffer-gcc10
    working_dir: /root
    volumes:
      - ./:/root/app
    environment:
      DEV_ENV: gcc10.1-test
    tty: true