version: "3.7"

services:
  app:
    image: machineplay/gcc10-standard-env
    command: sh -c "mkdir  /root/app/test/testbuild && cd /root/app/test/testbuild  &&  cmake .. && make -j8 && ./DoubleBufferTest"
    container_name: gcc10-unittest-env
    working_dir: /root
    volumes:
      - ./:/root/app
    environment:
      DEV_ENV: gcc10-test