version: "3.7"

services:
  app:
    image: machineplay/gcc10-standard-env
    command: sh -c "cd /root/app/test/build  &&  cmake .. && make -j8 && cp ./bin/gctest ./ && ./gctest"
    container_name: gcc10-unittest-env
    working_dir: /root
    volumes:
      - ./:/root/app
    environment:
      DEV_ENV: gcc10-test